### ISSUE TITLE
firefox 45 support

### ISSUE THREAD

**Issue by revilossor** [alphagov/openregister-location-picker#7]
Hi @tvararu - could you please update the accessible-autocomplete version to 1.2.1 and publish a new version? 

v1.2.1 has changes to make progressive enhancement work in firefox 45.

Thanks

**Comment by tvararu** [comment]
@revilossor Yes! Sorry, I need some automation around this.

**Comment by tvararu** [comment]
Done! Please use `v0.2.1`.

Opened https://github.com/alphagov/openregister-location-picker/issues/8.

**Comment by revilossor** [comment]
thank you
